# Generated by Django 5.1.3 on 2025-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "no",
                    models.IntegerField(
                        db_column="No", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("男", "男"), ("女", "女")],
                        db_column="Gender",
                        max_length=100,
                    ),
                ),
                ("birthday", models.DateField(db_column="Birthday")),
                ("mobile", models.CharField(db_column="Mobile", max_length=100)),
                ("password", models.CharField(db_column="Password", max_length=100)),
                ("email", models.CharField(db_column="Email", max_length=100)),
                ("address", models.CharField(db_column="Address", max_length=200)),
                (
                    "career",
                    models.CharField(db_column="Career", max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "User",
                "managed": True,
            },
        ),
    ]
